# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, libarchive, conduit, resourcet, transformers }:

cabal.mkDerivation (self: {
  pname = "libarchive-conduit";
  version = "0.1.0.0";
  src = ./.;
  buildDepends = [ conduit resourcet transformers ];
  extraLibraries = [ libarchive ];
  meta = {
    description = "Stream archives with conduit and libarchive";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
